
TRUNCATE TABLE cdm.care_site;
COPY cdm.care_site FROM 'data/eunomia/care_site.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.cdm_source;
COPY cdm.cdm_source FROM 'data/eunomia/cdm_source.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.cohort;
COPY cdm.cohort FROM 'data/eunomia/cohort.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.cohort_attribute;
COPY cdm.cohort_attribute FROM 'data/eunomia/cohort_attribute.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.concept;
COPY cdm.concept FROM 'data/eunomia/concept.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.concept_ancestor;
COPY cdm.concept_ancestor FROM 'data/eunomia/concept_ancestor.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.concept_class;
COPY cdm.concept_class FROM 'data/eunomia/concept_class.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.concept_relationship;
COPY cdm.concept_relationship FROM 'data/eunomia/CONcept_relationship.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.concept_synonym;
COPY cdm.concept_synonym FROM 'data/eunomia/concept_synonym.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.condition_era;
COPY cdm.condition_era FROM 'data/eunomia/condition_era.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.condition_occurrence;
COPY cdm.condition_occurrence FROM 'data/eunomia/CONdition_occurrence.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.cost;
COPY cdm.cost FROM 'data/eunomia/cost.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.death;
COPY cdm.death FROM 'data/eunomia/death.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.device_exposure;
COPY cdm.device_exposure FROM 'data/eunomia/device_exposure.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.domain;
COPY cdm.domain FROM 'data/eunomia/domain.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.dose_era;
COPY cdm.dose_era FROM 'data/eunomia/dose_era.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.drug_era;
COPY cdm.drug_era FROM 'data/eunomia/drug_era.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.drug_exposure;
COPY cdm.drug_exposure FROM 'data/eunomia/drug_exposure.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.drug_strength;
COPY cdm.drug_strength FROM 'data/eunomia/drug_strength.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.fact_relationship;
COPY cdm.fact_relationship FROM 'data/eunomia/fact_relationship.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.location;
COPY cdm.location FROM 'data/eunomia/location.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.measurement;
COPY cdm.measurement FROM 'data/eunomia/measurement.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.metadata;
COPY cdm.metadata FROM 'data/eunomia/metadata.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.note;
COPY cdm.note FROM 'data/eunomia/note.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.note_nlp;
COPY cdm.note_nlp FROM 'data/eunomia/note_nlp.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.observation;
COPY cdm.observation FROM 'data/eunomia/observation.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.observation_period;
COPY cdm.observation_period FROM 'data/eunomia/Observation_period.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.payer_plan_period;
COPY cdm.payer_plan_period FROM 'data/eunomia/payer_plan_period.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.person;
COPY cdm.person FROM 'data/eunomia/person.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.procedure_occurrence;
COPY cdm.procedure_occurrence FROM 'data/eunomia/PROcedure_occurrence.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.provider;
COPY cdm.provider FROM 'data/eunomia/provider.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.relationship;
COPY cdm.relationship FROM 'data/eunomia/relationship.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.source_to_concept_map;
COPY cdm.source_to_concept_map FROM 'data/eunomia/SOURce_to_concept_map.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.specimen;
COPY cdm.specimen FROM 'data/eunomia/specimen.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.visit_detail;
COPY cdm.visit_detail FROM 'data/eunomia/visit_detail.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.visit_occurrence;
COPY cdm.visit_occurrence FROM 'data/eunomia/visit_occurrence.csv' DELIMITER ',' CSV HEADER NULL AS '';
TRUNCATE TABLE cdm.vocabulary;
COPY cdm.vocabulary FROM 'data/eunomia/vocabulary.csv' DELIMITER ',' CSV HEADER NULL AS '';